spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Root@1234
  liquibase:
    change-log: classpath:/liquibase/master.xml
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML5
    cache: false
  application:
    name: t-blog
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xsh.blog.dao
server:
  port: 8080